export const SKILLSET_CONTENT = [
  {
    id: "qualification",
    tech: "ビジネス実務法務検定試験 3級",
    level: 3,
    explain: "2019年6月取得",
  },
  {
    id: "qualification",
    tech: "日商簿記検定 3級",
    level: 3,
    explain: "2019年6月取得",
  },
  {
    id: "qualification",
    tech: "基本情報技術者試験",
    level: 3,
    explain: "2019年10月取得",
  },
  {
    id: "qualification",
    tech: "応用情報技術者試験",
    level: 3,
    explain: "2020年10月取得",
  },
  {
    id: "qualification",
    tech: "AWS Certified Solutions Architect Associate",
    level: 3,
    explain: "2023年4月取得",
  },
  {
    id: "front",
    tech: "HTML",
    level: 3,
    explain: "基本的な利用方法に加え応用が可能で、他者へ教えることができる。",
  },
  {
    id: "front",
    tech: "CSS",
    level: 3,
    explain: "基本的な利用方法に加え応用が可能で、他者へ教えることができる。",
  },
  {
    id: "front",
    tech: "Javascript",
    level: 3,
    explain: "基本的な利用方法に加え応用が可能で、他者へ教えることができる。",
  },
  {
    id: "front",
    tech: "Typescript",
    level: 3,
    explain: "基本的な利用方法に加え応用が可能で、他者へ教えることができる。",
  },
  {
    id: "front",
    tech: "React",
    level: 2,
    explain: "基本的な利用方法を理解し、プロジェクトにて活用できる。",
  },
  {
    id: "front",
    tech: "Next.js",
    level: 2,
    explain: "基本的な利用方法を理解し、プロジェクトにて活用できる。",
  },
  {
    id: "front",
    tech: "Material UI",
    level: 2,
    explain: "基本的な利用方法を理解し、プロジェクトにて活用できる。",
  },
  {
    id: "back",
    tech: "Java",
    level: 2,
    explain: "基本的な利用方法を理解し、プロジェクトにて活用できる。",
  },
  {
    id: "back",
    tech: "Node.js",
    level: 2,
    explain: "基本的な利用方法を理解し、プロジェクトにて活用できる。",
  },
  {
    id: "back",
    tech: "SQL",
    level: 2,
    explain: "アプリケーション開発・運用にて、適切なSQL文を作成できる。",
  },
  {
    id: "back",
    tech: "Linux",
    level: 2,
    explain: "シェルを通しての操作、シェルスクリプトの作成が可能。",
  },
  {
    id: "back",
    tech: "AWS",
    level: 1,
    explain: "基礎的な環境構築が可能。学習中。",
  },
  {
    id: "other",
    tech: "GitHub",
    level: 3,
    explain: "基本的な利用方法に加え応用が可能で、他者へ教えることができる。",
  },
  {
    id: "other",
    tech: "SEO対策",
    level: 1,
    explain: "概要を理解し、設計・実装に活かすことができる。",
  },
];